name: conext-app
services:
  user-service:
    container_name: user-service
    platform: linux/amd64
    # image: sikoding20/user-service:17
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8081"
    env_file:
      - .env